UniChatApplication/Models/RoomChat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace UniChatApplication.Models
{
    [Table("room_chat")]
    public class RoomChat
    {
        //ID Property
        [Key]
        public int Id { get; set; }
        //ClassId Property
        [Column("class_id")]
        [ForeignKey("Class")]
        public int ClassId { get; set; }
        //Get and Set Class
        public Class Class { get; set; }
        //SubjectId Property
        [Column("subject_id")]
        [ForeignKey("Subject")]
        public int SubjectId { get; set; }
        //Get and Set Subject
        public Subject Subject { get; set; }
        //TeacherId Property
        [Column("teacher_id")]
        [ForeignKey("TeacherProfile")]
        public int TeacherId { get; set; }
        //Get and Set TeacherProfile
        public TeacherProfile TeacherProfile { get; set; }
        //Get list RoomMessage
        [InverseProperty("RoomChat")]
        public ICollection<RoomMessage> Messages { get; set; }
        //Get list RoomDeadLine
        public ICollection<RoomDeadLine> DeadLines { get; set; }
        //Get list GroupChat
        [InverseProperty("RoomChat")]
        public ICollection<GroupChat> GroupChats { get; set; }

    }
}

UniChatApplication/Controllers/BoxController.cs
using Microsoft.AspNetCore.Mvc;
using UniChatApplication.Data;
using UniChatApplication.Daos;
using UniChatApplication.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Http;
using System;

namespace UniChatApplication.Controllers
{

    public class BoxController : Controller
    {


        readonly UniChatDbContext _context;
        public static readonly int numberOfMessagesOnEachLoad = 5;
        public static readonly int numberOfMessagesOnStartLoad = 10;

        public BoxController(UniChatDbContext context)
        {
            _context = context;
        }
        /// <summary>
        /// Mapping Index
        /// </summary>
        /// <returns>View Index of Box</returns>
        public IActionResult Index()
        {

            if (HttpContext.Session.GetString("Role") != "Student"
            && HttpContext.Session.GetString("Role") != "Teacher") return Redirect("/Home/");

            Account LoginUser = AccountDAOs.getLoginAccount(_context, HttpContext.Session);
            Profile LoginProfile = ProfileDAOs.GetProfile(_context, LoginUser);

            IEnumerable<RoomChat> RoomChats = RoomChatDAOs.getAllRoomChats(_context)
                                                .Where(room => (room.TeacherProfile.AccountID == LoginUser.Id) || (room.Class.StudentProfiles.Any(student => student.AccountID == LoginUser.Id)));

            IEnumerable<RoomDeadLine> roomDeadLineList = RoomDeadLineDAOs.GetAll(_context)
                                                            .Where(r => RoomChats.Any(rc => rc.Id == r.RoomId))
                                                            .OrderByDescending(r => r.ExpirationTime).Take(8);

            if (LoginUser.RoleName == "Student")
            {
                // Get GroupChat List if LoginUser is student

                List<GroupChat> GroupChats = new List<GroupChat>();
                IEnumerable<GroupManage> groupDatas = GroupManageDAOs.getAllGroupData(_context)
                .Where(d => d.StudentId == LoginProfile.Id && d.GroupChat.RoomChat.ClassId == ((StudentProfile)LoginProfile).ClassID);
                foreach (GroupManage item in groupDatas)
                {
                    GroupChats.Add(item.GroupChat);
                }

                ViewData["GroupChats"] = GroupChats;
            }

            ViewData["RoomChats"] = RoomChats;
            ViewData["LoginUser"] = LoginUser;
            ViewData["RoomDeadLineList"] = roomDeadLineList;

            return View(LoginProfile);
        }


        /// <summary>
        /// Mapping to RoomChat, send data to RoomChat
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View RoomChat of Box</returns>
        public IActionResult RoomChat(int? id)
        {

            if (HttpContext.Session.GetString("Role") != "Student"
            && HttpContext.Session.GetString("Role") != "Teacher") return Redirect("/Home/");
            if (id == null) return NotFound();

            Account LoginUser = AccountDAOs.getLoginAccount(_context, HttpContext.Session);
            Profile LoginProfile = ProfileDAOs.GetProfile(_context, LoginUser);

            // Get RoomChat List
            IEnumerable<RoomChat> RoomChats = RoomChatDAOs.getAllRoomChats(_context)
                                                .Where(room => (room.TeacherProfile.AccountID == LoginUser.Id) || (room.Class.StudentProfiles.Any(student => student.AccountID == LoginUser.Id)));

            // Get main RoomChat which is selected
            RoomChat RoomChat = RoomChats.FirstOrDefault(room => room.Id == id);
            if (RoomChat == null) return Redirect("/Home/");


            if (LoginUser.RoleName == "Student")
            {
                // Get GroupChat List if LoginUser is student

                List<GroupChat> GroupChats = new List<GroupChat>();
                IEnumerable<GroupManage> groupDatas = GroupManageDAOs.getAllGroupData(_context)
                .Where(d => d.StudentId == LoginProfile.Id && d.GroupChat.RoomChat.ClassId == ((StudentProfile)LoginProfile).ClassID);
                foreach (GroupManage item in groupDatas)
                {
                    GroupChats.Add(item.GroupChat);
                }

                ViewData["GroupChats"] = GroupChats;
            }
            else
            {
                // Get GroupChat List if LoginUser is Teacher
                IEnumerable<GroupChat> GroupChats = GroupChatDAOs.getAllGroupChats(_context)
                                                    .Where(g => g.RoomID == RoomChat.Id).OrderBy(g => g.Order)
                                                    .ToList();
                ViewData["GroupChats"] = GroupChats;
            }

            if (LoginUser.RoleName == "Student") ViewData["LoginProfile"] = (StudentProfile)LoginProfile;
            if (LoginUser.RoleName == "Teacher") ViewData["LoginProfile"] = (TeacherProfile)LoginProfile;

            ViewData["LoginUser"] = LoginUser;
            ViewData["RoomChats"] = RoomChats;
            ViewData["MessagePin"] = RoomMessagePinDAOs.GetMessagePinOfRoom(_context, RoomChat.Id);

            ViewData["Messages"] = RoomMessageDAOs.Take(_context, RoomChat.Id, 0, numberOfMessagesOnStartLoad);
            HttpContext.Session.SetInt32($"Room{RoomChat.Id}NumberOfMessageSended", numberOfMessagesOnStartLoad);


            return View(RoomChat);
        }


        /// <summary>
        /// Use to pin message into RoomChat
        /// </summary>
        /// <param name="roomMessageId"></param>
        /// <returns>View of PinMessage of Box</returns>
        public IActionResult PinMessage(int roomMessageId)
        {

            RoomMessage message = RoomMessageDAOs.getAll(_context).FirstOrDefault(m => m.Id == roomMessageId);
            if (message == null) return BadRequest();

            bool CheckMessageBelongGroupOfUser = false;

            Account LoginUser = AccountDAOs.getLoginAccount(_context, HttpContext.Session);
            Profile LoginProfile = ProfileDAOs.GetProfile(_context, LoginUser);

            if (LoginUser.RoleName == "Teacher")
            {
                CheckMessageBelongGroupOfUser = ((TeacherProfile)LoginProfile).RoomChats
                .Any(room => room.Id == message.RoomID);
            }
            // RoleName = "Student"
            else
            {
                CheckMessageBelongGroupOfUser = ((StudentProfile)LoginProfile).Class.RoomChats
                .Any(room => room.Id == message.RoomID);
            }

            if (!CheckMessageBelongGroupOfUser) return BadRequest();


            RoomMessagePin messagePin = RoomMessagePinDAOs.GetAllMessagePinOfRoom(_context, message.RoomID).FirstOrDefault(m => m.RoomMessage.Id == roomMessageId);

            if (messagePin == null)
            {
                messagePin = new RoomMessagePin()
                {
                    RoomMessageId = roomMessageId,
                    Time = DateTime.Now
                };
                _context.RoomMessagePins.Add(messagePin);
                _context.SaveChanges();
            }
            else
            {
                messagePin.Time = DateTime.Now;
                _context.RoomMessagePins.Update(messagePin);
                _context.SaveChanges();
            }

            return Ok(new { Content = message.Content, Time = messagePin.Time.ToShortTimeString() + " " + messagePin.Time.ToShortDateString() });
        }


        /// <summary>
        /// Mapping to GroupChat, send data to GroupChat
        /// </summary>
        /// <param name="id"></param>
        /// <returns>View GroupChat of Box</returns>
        public IActionResult GroupChat(int? id)
        {

            if (HttpContext.Session.GetString("Role") != "Student") return Redirect("/Home/");
            if (id == null) return NotFound();

            Account LoginUser = AccountDAOs.getLoginAccount(_context, HttpContext.Session);
            Profile LoginProfile = ProfileDAOs.GetProfile(_context, LoginUser);

            // Get RoomChat List
            IEnumerable<RoomChat> RoomChats = RoomChatDAOs.getAllRoomChats(_context)
                                                .Where(room => room.Class.StudentProfiles.Any(student => student.AccountID == LoginUser.Id));

            // Get GroupChat List
            IEnumerable<GroupChat> GroupChats = GroupChatDAOs.getAllGroupChats(_context)
                                                .Where(g => g.GroupManages.Any(m => m.StudentId == LoginProfile.Id))
                                                .ToList();
            ViewData["GroupChats"] = GroupChats;

            // Get main GroupChat which is selected
            GroupChat GroupChat = GroupChats.FirstOrDefault(g => g.Id == id);
            if (GroupChat == null) return NotFound();
            // Check groupChat if it contains LoginUser
            GroupManage groupData = GroupChat.GroupManages.FirstOrDefault(m => m.StudentId == LoginProfile.Id);
            if (groupData == null) return NotFound();

            ViewData["GroupRole"] = groupData.RoleText;

            if (LoginUser.RoleName == "Student") ViewData["LoginProfile"] = (StudentProfile)LoginProfile;
            if (LoginUser.RoleName == "Teacher") ViewData["LoginProfile"] = (TeacherProfile)LoginProfile;

            ViewData["LoginUser"] = LoginUser;
            ViewData["RoomChats"] = RoomChats;
            ViewData["MessagePin"] = GroupMessagePinDAOs.GetMessagePinOfGroup(_context, GroupChat.Id);
            // Load Messages
            ViewData["Messages"] = GroupMessageDAOs.Take(_context, GroupChat.Id, 0, numberOfMessagesOnStartLoad);
            HttpContext.Session.SetInt32($"Group{GroupChat.Id}NumberOfMessageSended", numberOfMessagesOnStartLoad);

            return View(GroupChat);
        }

        /// <summary>
        /// Use to pin message into GroupChat
        /// </summary>
        /// <param name="groupMessageId"></param>

UniChatApplication/Views/RoomChat/Create.cshtml
@model UniChatApplication.Models.RoomChat

@{
    ViewData["Title"] = "RoomChat - Create";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="~/css/cssPlus/buttonPlus.css">
<link rel="stylesheet" href="~/css/RoomChatManagement/StyleCreate.css">


<div class="container">
    <form asp-action="Create" method="POST">
        <h1 class="text-center text-primary">Create New RoomChat</h1>
        <hr>
        <div class="spacer"></div>
        <p asp-validation-summary="ModelOnly" class="text-danger">@ViewBag.Error</p>
        <div class="form-group">
            <label asp-for="ClassId" class="control-label">Class</label>
            <select asp-for="ClassId" class ="form-control" asp-items="ViewBag.ClassId"></select>
        </div>
        <div class="form-group">
            <label asp-for="SubjectId" class="control-label">Subject</label>
            <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
        </div>
        <div class="form-group">
            <label asp-for="TeacherId" class="control-label">Teacher</label>
            <select asp-for="TeacherId" class ="form-control" asp-items="ViewBag.TeacherId"></select>
        </div>
        <div class="d-flex flex-column">
            <!-- button submit -->
            <button type="submit" class="form-submit button-2">
                <i class="fa fa-check"></i>
                <span>Add</span>
            </button>
        </div>
    </form>

    <!-- button back to menu -->
    <a asp-action="Index" id="btn-cancel" class="button-3 text-white text-decoration-none">
        <i class="fa fa-times"></i>
        <span>Back to List</span>
    </a>

</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniChatApplication/Views/RoomChat/Delete.cshtml
@model UniChatApplication.Models.RoomChat

@{

    ViewData["Title"] = "RoomChat - Delete";
}

<link rel="stylesheet" href="~/css/cssPlus/buttonPlus.css">
<link rel="stylesheet" href="~/css/RoomChatManagement/StyleDelete.css">


<div class="container">
    <div class="text-center">
        <h1 class="text-primary">RoomChat Management</h1>
        <hr>
        <a class="button-3 text-white text-decoration-none" asp-action="Index">Back to List</a>
        <hr>
        <h4 class="text-danger">Do you really want to delete this room?</h4>
        <form method="post" class="mt-3">
            <input type="submit" class="btn btn-outline-danger" value="Confirm">
        </form>
    </div>
    <hr>
    <div class="content">
        <div class="left-content">
            <h4 class="text-center text-success">Roomchat</h4>
            <ul>
                <li>ID: @Model.Id</li>
                <li>ClassName: @Model.Class.Name</li>
                <li>Subject: @Model.Subject.SubjectCode - @Model.Subject.FullName</li>
                <li>Lecture: @Model.TeacherProfile.FullName</li>
            </ul>
            <h4 class="text-center text-success">Groups in this room</h4>
            <ul>
                @foreach (GroupChat item in ViewBag.GroupChats)

                {
                    <li>@item.Name</li>

                }
            </ul>
        </div>
        <div class="right-content">
            <h4 class="text-center text-info">List of students of this room</h4>
            <table class="table table-bordered text-center">
                <thead class="bg-info">
                    <th>Avatar</th>
                    <th>StudentCode</th>
                    <th>FullName</th>
                </thead>
                <tbody>
                    @foreach (StudentProfile item in Model.Class.StudentProfiles)

                    {
                        <tr>
                            <td>
                                <img class="avatar" src="@item.Avatar" alt="">
                            </td>
                            <td>
                                @item.StudentCode
                            </td>
                            <td>
                                @item.FullName
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

UniChatApplication/Views/RoomChat/Details.cshtml
@model UniChatApplication.Models.RoomChat

@{

    ViewData["Title"] = "RoomChat - ViewDetail";
}
<link rel="stylesheet" href="~/css/cssPlus/buttonPlus.css">
<link rel="stylesheet" href="~/css/RoomChatManagement/StyleDetails.css">

<div class="container">
    <div class="text-center">
        <h1 class="text-primary">RoomChat Management</h1>
        <h4 >Detail for a roomchat</h4>
        @if (ViewBag.LoginUser.RoleName == "Admin")
        {
            <a class="button-3 text-white text-decoration-none" asp-action="Index">Back</a>

        }

        else
        {
            <a class="button-3 text-white text-decoration-none" asp-controller="Box" asp-action="RoomChat"
            asp-route-id="@Model.Id">Back</a>

        }
    </div>

    <hr>
    <div class="content">
        <div class="left-content">
            <h4 class="text-center text-success">Roomchat</h4>
            <ul>
                <li>ID: @Model.Id</li>
                <li>ClassName: @Model.Class.Name</li>
                <li>Subject: @Model.Subject.SubjectCode - @Model.Subject.FullName</li>
                <li>Lecture: @Model.TeacherProfile.FullName</li>
            </ul>
            <h4 class="text-center text-success">Groups in this room</h4>
            <ul>
                @foreach (GroupChat item in ViewBag.GroupChats)

                {
                    <li>
                        <a asp-controller="GroupChat" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
                    </li>

                }
            </ul>
        </div>
        <div class="right-content">
            <h4 class="text-center text-info">List of students of this room</h4>
            <table class="table table-bordered text-center">
                <thead class="bg-info">
                    <th>Avatar</th>
                    <th>StudentCode</th>
                    <th>FullName</th>
                </thead>
                <tbody>
                    @foreach (StudentProfile item in Model.Class.StudentProfiles)

                    {
                        <tr>
                            <td>
                                <img class="avatar" src="@item.Avatar" alt="avatar">
                            </td>
                            <td>
                                @item.StudentCode
                            </td>
                            <td>
                                @item.FullName
                            </td>
                        </tr>

                    }
                </tbody>
            </table>
        </div>
    </div>

</div>

UniChatApplication/Views/RoomChat/Edit.cshtml
@model UniChatApplication.Models.RoomChat

@{
    ViewData["Title"] = "RoomChat - Edit";
}

<link rel="stylesheet" href="~/css/cssPlus/buttonPlus.css">
<link rel="stylesheet" href="~/css/RoomChatManagement/StyleEdit.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



<div class="container">
    <form asp-action="Edit" method="POST">
        <h1 class="text-center text-primary">Edit RoomChat</h1>
        <hr>
        <div class="spacer"></div>
        <p asp-validation-summary="ModelOnly" class="text-danger">@ViewBag.Error</p>
        <div class="form-group">
            <label asp-for="ClassId" class="control-label">Class</label>
            <select asp-for="ClassId" class="form-control" asp-items="ViewBag.ClassId"></select>
            <span asp-validation-for="ClassId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="SubjectId" class="control-label">Subject</label>
            <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
            <span asp-validation-for="SubjectId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="TeacherId" class="control-label">Teacher</label>
            <select asp-for="TeacherId" class="form-control" asp-items="ViewBag.TeacherId"></select>
            <span asp-validation-for="TeacherId" class="text-danger"></span>
        </div>
        <div class="d-flex flex-column">
            <!-- button submit -->
            <button type="submit" class="form-submit button-2 text-white text-decoration-none">
                <i class="fa fa-check"></i>
                <span>Save</span>
            </button>
        </div>
        
    </form>

    <!-- button back to menu -->
    <a asp-action="Index" id="btn-cancel" class="button-3 text-white text-decoration-none">
        <i class="fa fa-times"></i>
        <span>Back to List</span>
    </a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

UniChatApplication/Views/RoomChat/Index.cshtml
@model IEnumerable<UniChatApplication.Models.RoomChat>

@{
    ViewData["Title"] = "RoomChatManagement";
}

@* Link CSS *@
<link rel="stylesheet" href="~/css/RoomChatManagement/StyleIndex.css">
<link rel="stylesheet" href="~/css/cssPlus/buttonPlus.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css">

    <div class="container">
        <br>
        <div class="box">
            <h1 class="text-center">RoomChat Management</h1>
            <hr>
            <div>
                <div class="row text-center">
                    <div class="col-sm-6">
                        <a class="button-2 w-50 text-decoration-none text-white" asp-action="Create">Create</a>
                    </div>
                    <div class="col-sm-6">
                        <a class="button-3 w-50 text-decoration-none text-white" asp-controller="Admin"
                            asp-action="Index">Back to Admin</a>
                    </div>
                </div>

            </div>
            <hr>

            <h2 class="text-center">List Of RoomChats</h2>
            <table class="table table-bordered text-center" id="room-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Class</th>
                        <th>Subject</th>
                        <th>Teacher</th>
                        <th>Operation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (RoomChat item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td>@item.Class.Name</td>
                            <td>@item.Subject.FullName</td>
                            <td>@item.TeacherProfile.FullName</td>
                            <td class="d-flex justify-content-center" style="gap: 1rem;">
                                <a class="button-2 text-decoration-none text-white" asp-action="Edit"
                                asp-route-id="@item.Id">
                                    <ion-icon name="create-outline"></ion-icon>
                                </a>
                                <a class="button-1 text-decoration-none text-white" asp-action="Details"
                                asp-route-id="@item.Id">
                                    <ion-icon name="information-circle-outline"></ion-icon>
                                </a>
                                <a class="button-3 text-decoration-none text-white" asp-action="Delete"
                                asp-route-id="@item.Id">
                                    <ion-icon name="trash-outline"></ion-icon>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

<script>

    $(document).ready(function(){

        $('#room-table').DataTable({
            "language": {
                "lengthMenu": "_MENU_",
                "zeroRecords": "No data matching",
                "info": "_PAGE_/_PAGES_",
                "infoEmpty": "",
                "infoFiltered": ""
            }
        });
    })

</script>
@* Datatable link scripts *@
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js"></script>
@* ionicon link scripts *@
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>